crispy/urls.py
from django.urls import path

from crispy.views import PersonCreateView, PersonUpdateView, PersonListView, PersonDeleteView

app_name = 'crispy'

urlpatterns = [
	path('', PersonListView.as_view(), name='list'),
	path('add/', PersonCreateView.as_view(), name='add'),
	path('edit/<int:pk>/', PersonUpdateView.as_view(), name='edit'),
	path('delete/<int:pk>/', PersonDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('crispy.urls'))
]

crispy/models.py
from django.db import models


# Create your models here.
from django.urls import reverse_lazy


class Person(models.Model):
	name = models.CharField(max_length=130)
	email = models.EmailField(blank=True)
	job_title = models.CharField(max_length=30, blank=True)
	bio = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Kişi'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse_lazy('crispy:list')

crispy/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from crispy.models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'email', 'job_title', 'bio')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))
       

crispy/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from crispy.forms import PersonForm
from crispy.models import Person


class PersonCreateView(CreateView):
	model = Person
	fields = ('name', 'email', 'job_title', 'bio')
	template_name = "crispy/person_form.html"


class PersonUpdateView(UpdateView):
	model = Person
	form_class = PersonForm
	template_name = 'crispy/person_update_form.html'


class PersonListView(ListView):
	model = Person
	template_name = "crispy/person_list.html"
	context_object_name = "people_list"
	# paginate_by = 10


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['date'] = timezone.now()
		return context


class PersonDeleteView(DeleteView):
	model = Person
	template_name = "crispy/person_confirm_delete.html"
	success_url = reverse_lazy('crispy:list')

crispy/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
				integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
				integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<title>Persons</title>
</head>
<body>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-8">
			<h1 class="mt-2">Persons</h1>
			<hr class="mt-0 mb-8">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</div>
</body>
</html>

crispy/templates/crispy/person_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
	<form method="post">{% csrf_token %}
		<div class="form-group">
			<p> Are you sure you want to delete "{{ object.name }}" ?</p>
			<input type="submit" class="btn btn-danger" value="Confirm">
		</div>
	</form>
{% endblock %}

crispy/templates/crispy/person_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

**people/person_form.html**

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="row">
      <div class="col-6">
        {{ form.name|as_crispy_field }}
      </div>
      <div class="col-6">
        {{ form.email|as_crispy_field }}
      </div>
    </div>
    {{ form.job_title|as_crispy_field }}
    {{ form.bio|as_crispy_field }}
    <a href="{% url 'crispy:list' %}" class="btn btn-primary">Back</a>
    <button type="submit" class="btn btn-success">Save person</button>
  </form>
{% endblock %}

crispy/templates/crispy/person_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="float-right">
		<a class="btn btn-success" href="{% url 'crispy:add' %}"><i class="fa fa-plus"></i>Add Person</a>
	</div>
	<br><br><br>
	<div class="row">

		{% for person in people_list %}
		<div class="col-6">
			<div class="card" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title">{{ person.name }} - {{ person.job_title }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{ person.email }}</h6>
					<p class="card-text">{{ person.bio }}</p>
					<div style="text-align: center">
						<a href="{% url 'crispy:edit' person.pk %}" class="btn btn-warning"><i
								class="fa fa-edit"></i></a>
						<a href="{% url 'crispy:delete' person.pk %}" class="btn btn-danger"><i
								class="fa fa-trash"></i></a>
					</div>
				</div>
			</div>
			<br>
		</div>
		{% endfor %}

	</div>
</div>

{% endblock %}

crispy/templates/crispy/person_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
  <a href="{% url 'crispy:list' %}" class="btn btn-primary">Back</a>
  <br>
{% endblock %}